import subprocess
#from snakemake.utils import R

def execcommand(cmd,stdout,stderr,input=""):
    with open(stdout, "w") as outf:
        with open (stderr, "w") as errf:
            o,e = subprocess.Popen(cmd, shell=True, stdout=outf, stderr=errf, universal_newlines=True).communicate(input)
            errf.close()
        outf.close()
    return o,e

obs = [str(i) for i in range(1,41)]

rule all:
    input:
        expand('3dvarnmc_data/{param}', param=obs),
        expand('kf6norm_obs_data/{param}', param=obs)

# rulename should not be begin by numbers
rule var3dnmc:
    params:
        1
    output:
        '3dvarnmc_data/{a}'
    log:
        '3dvarnmc_log/{a}'
    run:
        execcommand(expand('./3DVarNMC_inout.py {n}', n={wildcards.a}), output[0], log[0])

rule kf6norm_obs:
    params:
        1
    output:
        'kf6norm_obs_data/{a}'
    log:
        'kf6norm_obs_log/{a}'
    run:
        execcommand(expand('./KF6norm_obs_inout.py {n}', n={wildcards.a}), output[0], log[0])
